- hosts: aws_ec2_manager
  become: yes

  tasks:
    - name: Prepare statement with sysbench
      command: "sysbench oltp_read_write --table-size=1000000 --mysql-db=sakila --mysql-user=root --mysql-password=root prepare"

    - name: Execute performance test
      shell: "sysbench oltp_read_write --table-size=1000000 --mysql-db=sakila --mysql-user=root --mysql-password=root --threads=6 --time=60 --max-requests=0 run > /home/shared/cluster-result.log"

    - name: Display testbench results
      command: "cat /home/shared/cluster-result.log"

    - name: Fetch testbench result log to local machine
      fetch:
        src: "/home/shared/cluster-result.log"
        dest: "/Users/mazilious/git/LOG8415_Projet/src/terraform/benchmarks/"
        flat: yes

