- hosts: aws_ec2_proxy
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Nginx
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - python3
        - python3-pip

    - name: Start Nginx service
      service:
        name: nginx
        state: started

    - name: Ensure Nginx is enabled and starts on boot
      systemd:
        name: nginx
        enabled: yes

    - name: Copy folder using copy module
      ansible.builtin.copy:
        src: "/Users/mazilious/git/LOG8415_Projet/src/terraform/cluster/.ssh"
        dest: "/home/app/"

    - name: Copy folder using copy module
      ansible.builtin.copy:
        src: "/Users/mazilious/git/LOG8415_Projet/src/apps/proxy/main.py"
        dest: "/home/app/"

