name: Trusted Host - Docker Build and Push

on:
  push:
    paths:
      - 'src/apps/trusted_host/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        cd src/apps/proxy
        docker build . --tag mazil007/mf-trusted_host:latest

    - name: Login to Docker Hub (optional)
      if: success()
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/mf-trusted_host:latest
